;; -*- lexical-binding: t -*-
;;; custom.el --- Emacs custom-set-variables -*- lexical-binding: t -*-
;;; Commentary:
;; This file is auto-generated by Emacs custom system.
;;; Code:

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-enabled-themes '(sanityinc-tomorrow-bright))
 '(custom-safe-themes
   '("b11edd2e0f97a0a7d5e66a9b82091b44431401ac394478beb44389cf54e6db28"
     default))
 '(package-selected-packages
   '(ag color-theme-sanityinc-solarized color-theme-sanityinc-tomorrow
     company consult-lsp counsel csv-mode diff-hl diminish dimmer diredfl
     exec-path-from-shell expand-region fullframe gnu-elpa-keyring-update
     go-mode grab-mac-link ibuffer-vc ivy ivy-historian ivy-xref lsp-mode
     lsp-pyright lsp-ui lua-mode magit markdown-mode org-cliplink org-pomodoro
     projectile py-autopep8 rust-mode seq swiper typescript-mode undo-tree
     vterm web-mode winum writeroom-mode yaml-mode yasnippet)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

(put 'erase-buffer 'disabled nil)

;;; custom.el ends here
